=== ProjectRemyx/Jing-s-XML-Chatroom/chatrooms.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="chatrooms">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="chatroom" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="chatroomName" type="xs:string"/>
                            <xs:element name="chatroomAvatar">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="image" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="name" type="xs:string" use="required"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="chatroomMembers" type="xs:positiveInteger"/>
                            <xs:element name="chatroomDescription" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ProjectRemyx/Jing-s-XML-Chatroom/Chatrooms/chatroomsList.xml
<?xml version="1.0" encoding="utf-8"?>
<chatrooms xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="chatrooms.xsd">
    <chatroom id="1">
        <chatroomName>The Three Musketeers</chatroomName>
        <chatroomAvatar>
            <image name="Room avatar">image.jpg</image>
        </chatroomAvatar>
        <chatroomMembers>3</chatroomMembers>
        <chatroomDescription>Jing, Kento and Justin's hangout</chatroomDescription>
    </chatroom>
    <chatroom id="2">
        <chatroomName>Jingy's MapleStory Chat</chatroomName>
        <chatroomAvatar>
            <image name="Room avatar">image2.jpg</image>
        </chatroomAvatar>
        <chatroomMembers>10</chatroomMembers>
        <chatroomDescription>A place where you can talk about your favorite game, MapleStory!</chatroomDescription>
    </chatroom>
</chatrooms>
