=== ProjectRemyx/Jing-s-XML-Chatroom/Chatrooms/chatroom.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="chatroom">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="chat" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="user" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="status" type="xs:string"/>
                                        <xs:element name="avatar" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="image" maxOccurs="1">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="name" type="xs:string" use="required"/>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="message" minOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="submissionTime" type="xs:time"/>
                                                    <xs:element name="text" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ProjectRemyx/Jing-s-XML-Chatroom/Chatrooms/chatroom1.xml
<?xml version="1.0" encoding="utf-8"?>
<chatroom xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="chatroom.xsd">
    <chat id="1">
        <user id="1">
            <name>Jing</name>
            <status>Online</status>
            <avatar>
                <image name="Avatar picture">avatar.jpg</image>
            </avatar>
            <message>
                <submissionTime>07:00:00</submissionTime>
                <text>Hey</text>
            </message>
        </user>
        <user id="2">
            <name>Kento</name>
            <status>Busy</status>
            <message>
                <submissionTime>07:30:00</submissionTime>
                <text>Busy doing the XML assignment</text>
            </message>
        </user>
        <user id="3">
            <name>Justin</name>
            <status>Away</status>
            <message>
                <submissionTime>07:31:00</submissionTime>
                <text>Same</text>
            </message>
        </user>
    <user id="1"><name>Jing</name><message><submissionTime>Mar,30,2019 06:06:02 AM</submissionTime><text>ok</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Mar,30,2019 06:08:02 AM</submissionTime><text>fine</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Mar,30,2019 06:09:07 AM</submissionTime><text>D:</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Mar,30,2019 06:11:47 AM</submissionTime><text>i hate u</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Mar,30,2019 06:25:33 AM</submissionTime><text>PLEASE WORK</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Mar,30,2019 06:25:35 AM</submissionTime><text>PLEASE WORK</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Mar,30,2019 06:26:13 AM</submissionTime><text>Can you refresh</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Mar,30,2019 06:26:17 AM</submissionTime><text>OMG IS IT WORKING</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Mar,30,2019 06:26:21 AM</submissionTime><text>YESSSSSSSSSSSSSSSSSSS</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Mar,30,2019 06:36:58 AM</submissionTime><text>Testing</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Mar,30,2019 06:38:27 AM</submissionTime><text>Testing back button</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Mar,30,2019 06:42:51 AM</submissionTime><text>Final Test</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Apr,05,2019 12:11:34 AM</submissionTime><text>Assignment 3 first test login with encryption/salt</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Apr,05,2019 01:01:47 AM</submissionTime><text>test</text></message></user><user id="1"><name>Architekx</name><message><submissionTime>Apr,05,2019 02:43:01 AM</submissionTime><text>Testing google sign in</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Apr,05,2019 02:43:27 AM</submissionTime><text>Testing google sign out and sign in to new account</text></message></user><user id="1"><name>Kento</name><message><submissionTime>Apr,05,2019 09:48:17 PM</submissionTime><text>Testing Ajax Refresh</text></message></user><user id="1"><name>Kento</name><message><submissionTime>Apr,05,2019 09:48:44 PM</submissionTime><text>Testing Ajax Refresh2</text></message></user><user id="1"><name>Justin</name><message><submissionTime>Apr,05,2019 09:56:29 PM</submissionTime><text>Testing Ajax Refresh 3</text></message></user><user id="1"><name>Justin</name><message><submissionTime>Apr,05,2019 09:58:09 PM</submissionTime><text>Testing Ajax Refresh 3</text></message></user><user id="1"><name>Justin</name><message><submissionTime>Apr,05,2019 09:58:14 PM</submissionTime><text>Testing Ajax Refresh 4</text></message></user><user id="1"><name>Justin</name><message><submissionTime>Apr,05,2019 10:06:54 PM</submissionTime><text>Testing Ajax Refresh 5</text></message></user><user id="1"><name>Justin</name><message><submissionTime>Apr,05,2019 10:07:34 PM</submissionTime><text>Ajax is refreshing the page but not seeing the updated chatroom</text></message></user><user id="1"><name>Justin</name><message><submissionTime>Apr,05,2019 10:07:47 PM</submissionTime><text/></message></user><user id="1"><name>Architekx</name><message><submissionTime>Apr,05,2019 10:15:02 PM</submissionTime><text>Is Ajax working?</text></message></user><user id="1"><name>Architekx</name><message><submissionTime>Apr,05,2019 10:15:31 PM</submissionTime><text>Testing?</text></message></user><user id="1"><name>Architekx</name><message><submissionTime>Apr,05,2019 10:30:25 PM</submissionTime><text>Is AJax working now?</text></message></user><user id="1"><name>Architekx</name><message><submissionTime>Apr,05,2019 10:42:19 PM</submissionTime><text>Testing Ajax!!</text></message></user><user id="1"><name>Architekx</name><message><submissionTime>Apr,05,2019 10:45:05 PM</submissionTime><text>Ajax is working!!!</text></message></user><user id="1"><name>Architekx</name><message><submissionTime>Apr,05,2019 10:45:28 PM</submissionTime><text>This chat should refresh every 250 milliseconds</text></message></user><user id="1"><name>Architekx</name><message><submissionTime>Apr,06,2019 06:11:07 AM</submissionTime><text>Testing refresh</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Apr,06,2019 07:45:08 PM</submissionTime><text>Testing again</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Apr,06,2019 08:07:14 PM</submissionTime><text>jing</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Apr,06,2019 10:57:31 PM</submissionTime><text>Testing sending a message after moving code around</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Apr,06,2019 10:57:41 PM</submissionTime><text>is this refreshing the page?</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Apr,06,2019 10:59:39 PM</submissionTime><text>test</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Apr,06,2019 11:06:42 PM</submissionTime><text>test</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Apr,06,2019 11:12:54 PM</submissionTime><text>sd</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Apr,06,2019 11:14:13 PM</submissionTime><text>message</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Apr,06,2019 11:23:34 PM</submissionTime><text>qwe</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Apr,06,2019 11:24:05 PM</submissionTime><text>testing</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Apr,06,2019 11:35:08 PM</submissionTime><text>test</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Apr,06,2019 11:35:31 PM</submissionTime><text>php</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Apr,06,2019 11:38:34 PM</submissionTime><text>do not refresh</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Apr,06,2019 11:39:24 PM</submissionTime><text/></message></user><user id="1"><name>Jing</name><message><submissionTime>Apr,06,2019 11:39:56 PM</submissionTime><text/></message></user><user id="1"><name>Jing</name><message><submissionTime>Apr,06,2019 11:40:05 PM</submissionTime><text/></message></user><user id="1"><name>Jing</name><message><submissionTime>Apr,06,2019 11:40:18 PM</submissionTime><text>why no work</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Apr,06,2019 11:48:00 PM</submissionTime><text/></message></user><user id="1"><name>Jing</name><message><submissionTime>Apr,06,2019 11:50:52 PM</submissionTime><text/></message></user><user id="1"><name>Jing</name><message><submissionTime>Apr,06,2019 11:51:02 PM</submissionTime><text/></message></user><user id="1"><name>Jing</name><message><submissionTime>Apr,06,2019 11:52:11 PM</submissionTime><text/></message></user><user id="1"><name>Jing</name><message><submissionTime>Apr,07,2019 12:12:12 AM</submissionTime><text>why doesnt this work</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Apr,07,2019 12:14:44 AM</submissionTime><text>please</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Apr,07,2019 12:14:50 AM</submissionTime><text>omg</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Apr,07,2019 12:15:18 AM</submissionTime><text>does this work</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Apr,07,2019 12:18:15 AM</submissionTime><text>please tell me this works</text></message></user><user id="1"><name>Jing</name><message><submissionTime>Apr,07,2019 12:18:18 AM</submissionTime><text>IT WORKS</text></message></user></chat>
</chatroom>

=== ProjectRemyx/Jing-s-XML-Chatroom/Chatrooms/chatroom2.xml
<?xml version="1.0" encoding="utf-8"?>
<chatroom xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="chatroom.xsd">
    <chat id="1">
        <user id="1">
            <name>Jing</name>
            <status>Online</status>
            <avatar>
                <image name="Avatar picture">avatar.jpg</image>
            </avatar>
            <message>
                <submissionTime>07:00:00</submissionTime>
                <text>Hey, just started MapleStory M. It's sick!</text>
            </message>
        </user>
        <user id="2">
            <name>Jenny</name>
            <status>Busy</status>
            <message>
                <submissionTime>07:30:00</submissionTime>
                <text>Loser!</text>
            </message>
        </user>
        <user id="3">
            <name>Justin</name>
            <status>Away</status>
            <message>
                <submissionTime>07:31:00</submissionTime>
                <text>Stop playing MapleStory!!!</text>
            </message>
        </user>
    <user id="2"><name>Jing</name><message><submissionTime>Mar,30,2019 06:29:58 AM</submissionTime><text>Never</text></message></user><user id="2"><name>Jing</name><message><submissionTime>Mar,30,2019 06:38:35 AM</submissionTime><text>Testing back button</text></message></user><user id="2"><name>Jing</name><message><submissionTime>Mar,30,2019 06:43:53 AM</submissionTime><text>Final test</text></message></user></chat>
</chatroom>
